api:
  host: "HOST"
  port: "PORT"

services:
  foo:
    string: "STRING"
    int: "INT"
    float: "FLOAT"
    bool: "BOOL"
    multi_array:
      - "ONE"
      - "NON_EXISTING_VAR"
      - "TWO"
    single_array:
      - "ONE"

