api:
  host: "127.0.0.1"
  port: 8080

foo_service:
  foo_string: foo
  foo_int: 42
  foo_float: 9.81
  foo_bool: false

bar_service:
  bar_string: bar
  bar_int: 84
  bar_float: 3.141592
  bar_bool: false
